-- size of each column in runs table
select sum(pg_column_size(match_id)) / pg_table_size('runs')::float as match_id,
    sum(pg_column_size(season)) / pg_table_size('runs')::float as season,
    sum(pg_column_size(over)) / pg_table_size('runs')::float as over,
    sum(pg_column_size(ball_no)) / pg_table_size('runs')::float as ball_no,
    sum(pg_column_size(innings)) / pg_table_size('runs')::float as innings,
    sum(pg_column_size(batter)) / pg_table_size('runs')::float as batter,
    sum(pg_column_size(non_striker)) / pg_table_size('runs')::float as non_striker,
    sum(pg_column_size(bowler)) / pg_table_size('runs')::float as bowler,
    sum(pg_column_size(batter_runs)) / pg_table_size('runs')::float as batter_runs,
    sum(pg_column_size(extra_runs)) / pg_table_size('runs')::float as extra_runs,
    sum(pg_column_size(wide)) / pg_table_size('runs')::float as wide,
    sum(pg_column_size(noball)) / pg_table_size('runs')::float as noball,
    sum(pg_column_size(penalty)) / pg_table_size('runs')::float as penalty,
    sum(pg_column_size(wicket)) / pg_table_size('runs')::float as wicket,
    sum(pg_column_size(out_type)) / pg_table_size('runs')::float as out_type,
    sum(pg_column_size(fielders_involved)) / pg_table_size('runs')::float as fielders_involved,
    sum(pg_column_size(bowler_wicket)) / pg_table_size('runs')::float as bowler_wicket,
    sum(pg_column_size(boundaries)) / pg_table_size('runs')::float as boundaries
from runs;
-- size of each column in batter_stats_each_match table
select sum(pg_column_size(team_won)) / pg_table_size('batter_stats_each_match')::float as team_won,
    sum(pg_column_size(match_id)) / pg_table_size('batter_stats_each_match')::float as match_id,
    sum(pg_column_size(innings)) / pg_table_size('batter_stats_each_match')::float as innings,
    sum(pg_column_size(team_score)) / pg_table_size('batter_stats_each_match')::float as team_score,
    sum(pg_column_size(opposition_score)) / pg_table_size('batter_stats_each_match')::float as opposition_score,
    sum(pg_column_size(team)) / pg_table_size('batter_stats_each_match')::float as team,
    sum(pg_column_size(opposition)) / pg_table_size('batter_stats_each_match')::float as opposition,
    sum(pg_column_size(toss_won)) / pg_table_size('batter_stats_each_match')::float as toss_won,
    sum(pg_column_size(runs)) / pg_table_size('batter_stats_each_match')::float as runs,
    sum(pg_column_size(over)) / pg_table_size('batter_stats_each_match')::float as over,
    sum(pg_column_size(balls_faced)) / pg_table_size('batter_stats_each_match')::float as balls_faced,
    sum(pg_column_size(singles)) / pg_table_size('batter_stats_each_match')::float as singles,
    sum(pg_column_size(doubles)) / pg_table_size('batter_stats_each_match')::float as doubles,
    sum(pg_column_size(triples)) / pg_table_size('batter_stats_each_match')::float as triples,
    sum(pg_column_size(fours)) / pg_table_size('batter_stats_each_match')::float as fours,
    sum(pg_column_size(sixes)) / pg_table_size('batter_stats_each_match')::float as sixes,
    sum(pg_column_size(bowler_wicket)) / pg_table_size('batter_stats_each_match')::float as bowler_wicket,
    sum(pg_column_size(player)) / pg_table_size('batter_stats_each_match')::float as player,
    sum(pg_column_size(out_type)) / pg_table_size('batter_stats_each_match')::float as out_type,
    sum(pg_column_size(bowler)) / pg_table_size('batter_stats_each_match')::float as bowler,
    sum(pg_column_size(season)) / pg_table_size('batter_stats_each_match')::float as season,
    sum(pg_column_size(fielders_involved)) / pg_table_size('batter_stats_each_match')::float as fielders_involved
from batter_stats_each_match;
-- size of each table in ipl database
select pg_table_size('matches') as matches,
    pg_table_size('runs') as runs,
    pg_table_size('players') as players,
    pg_table_size('partnerships') as partnerships,
    pg_table_size('batter_stats_each_match') as batter_stats_each_match,
    pg_database_size('ipl') as ipl;