CREATE TABLE matches(
    match_id VARCHAR PRIMARY KEY,
    match_number VARCHAR,
    season VARCHAR,
    match_start_date VARCHAR,
    city VARCHAR,
    toss_won VARCHAR,
    toss_decision VARCHAR,
    is_super_over SMALLINT,
    team1 VARCHAR,
    team2 VARCHAR,
    team_won VARCHAR,
    won_by_wickets SMALLINT,
    won_by_runs SMALLINT,
    player_of_match VARCHAR,
    team1_score SMALLINT,
    team1_wickets SMALLINT,
    team1_fours SMALLINT,
    team1_sixes SMALLINT,
    team1_extras SMALLINT,
    team2_score SMALLINT,
    team2_wickets SMALLINT,
    team2_fours SMALLINT,
    team2_sixes SMALLINT,
    team2_extras SMALLINT
);

COPY matches(
match_id,
match_number,
season,
match_start_date,
city,
toss_won,
toss_decision,
is_super_over,
team1,
team2,
team_won,
won_by_wickets,
won_by_runs,
player_of_match,
team1_score,
team1_wickets,
team1_fours,
team1_sixes,
team1_extras,
team2_score,
team2_wickets,
team2_fours,
team2_sixes,
team2_extras
) FROM :MATCHES_FILE DELIMITER ',' CSV HEADER;
