psql -d ipl -c "
CREATE TYPE team_type AS ENUM (
'Deccan Chargers',
'Gujarat Lions',
'Delhi Capitals',
'Sunrisers Hyderabad',
'Gujarat Titans',
'Kolkata Knight Riders',
'Rising Pune Supergiants',
'Pune Warriors',
'Lucknow Super Giants',
'Royal Challengers Bangalore',
'Kochi Tuskers Kerala',
'Mumbai Indians',
'Chennai Super Kings',
'Kings XI Punjab',
'Rajasthan Royals'
);
"
psql -d ipl -c "CREATE TABLE matches(
    match_id_new SERIAL PRIMARY KEY,
    match_id VARCHAR UNIQUE,
    match_number VARCHAR,
    season VARCHAR,
    match_start_date VARCHAR,
    city VARCHAR,
    toss_won team_type,
    toss_decision VARCHAR,
    is_super_over SMALLINT,
    team1 team_type,
    team2 team_type,
    team_won team_type,
    won_by_wickets SMALLINT,
    won_by_runs SMALLINT,
    player_of_match VARCHAR,
    team1_score SMALLINT,
    team1_wickets SMALLINT,
    team1_fours SMALLINT,
    team1_sixes SMALLINT,
    team1_extras SMALLINT,
    team2_score SMALLINT,
    team2_wickets SMALLINT,
    team2_fours SMALLINT,
    team2_sixes SMALLINT,
    team2_extras SMALLINT
);"

psql -d ipl -c "\COPY matches(
match_id,
match_number,
season,
match_start_date,
city,
toss_won,
toss_decision,
is_super_over,
team1,
team2,
team_won,
won_by_wickets,
won_by_runs,
player_of_match,
team1_score,
team1_wickets,
team1_fours,
team1_sixes,
team1_extras,
team2_score,
team2_wickets,
team2_fours,
team2_sixes,
team2_extras
) FROM $1 DELIMITER ',' CSV HEADER;"
